---
title: "ML Course Project"
author: "Bill Cohee"
date: "April 16, 2016"
output: html_document
---
The goal of this exercise is to analyze some quantitative data collected from wearable devices of people who are exercising and then based on the data, come up with a qualitative prediction or classification, of how well they performed the exercises.

To begin, I downloaded and opened the training data in R.  Exploring the data I could see that there was some obvious noise in the data such as timestamps, user, new window, etc that would not be relevant for prediction purposes.  I trimmed these out by creating a new data frame that subsetted the original.  To further simplify and compress the data set, I used the nearZeroVar() function to determine which features would be poor predictors.  Turns out 60 columns in the data would be poor predictors. So, next I subsetted the data again removing the useless predictors:

```{}
library(caret)
nearzerovals<-nearZeroVar(trData2, saveMetrics=TRUE)
nearzerovals
                           freqRatio percentUnique zeroVar   nzv
roll_belt                   1.101904    6.77810621   FALSE FALSE
pitch_belt                  1.036082    9.37722964   FALSE FALSE
yaw_belt                    1.058480    9.97349913   FALSE FALSE
total_accel_belt            1.063160    0.14779329   FALSE FALSE
kurtosis_roll_belt       1921.600000    2.02323922   FALSE  TRUE
kurtosis_picth_belt       600.500000    1.61553358   FALSE  TRUE
kurtosis_yaw_belt          47.330049    0.01019264   FALSE  TRUE
skewness_roll_belt       2135.111111    2.01304658   FALSE  TRUE
skewness_roll_belt.1      600.500000    1.72255631   FALSE  TRUE
skewness_yaw_belt          47.330049    0.01019264   FALSE  TRUE
max_roll_belt               1.000000    0.99378249   FALSE FALSE
max_picth_belt              1.538462    0.11211905   FALSE FALSE
max_yaw_belt              640.533333    0.34654979   FALSE  TRUE
min_roll_belt               1.000000    0.93772296   FALSE FALSE
min_pitch_belt              2.192308    0.08154113   FALSE FALSE
min_yaw_belt              640.533333    0.34654979   FALSE  TRUE
amplitude_roll_belt         1.290323    0.75425543   FALSE FALSE
amplitude_pitch_belt        3.042254    0.06625217   FALSE FALSE
amplitude_yaw_belt         50.041667    0.02038528   FALSE  TRUE
var_total_accel_belt        1.426829    0.33126083   FALSE FALSE
avg_roll_belt               1.066667    0.97339721   FALSE FALSE
stddev_roll_belt            1.039216    0.35164611   FALSE FALSE
var_roll_belt               1.615385    0.48924676   FALSE FALSE
avg_pitch_belt              1.375000    1.09061258   FALSE FALSE
stddev_pitch_belt           1.161290    0.21914178   FALSE FALSE
var_pitch_belt              1.307692    0.32106819   FALSE FALSE
avg_yaw_belt                1.200000    1.22311691   FALSE FALSE
stddev_yaw_belt             1.693878    0.29558659   FALSE FALSE
var_yaw_belt                1.500000    0.73896647   FALSE FALSE
gyros_belt_x                1.058651    0.71348486   FALSE FALSE
gyros_belt_y                1.144000    0.35164611   FALSE FALSE
gyros_belt_z                1.066214    0.86127816   FALSE FALSE
accel_belt_x                1.055412    0.83579655   FALSE FALSE
accel_belt_y                1.113725    0.72877383   FALSE FALSE
accel_belt_z                1.078767    1.52379982   FALSE FALSE
magnet_belt_x               1.090141    1.66649679   FALSE FALSE
magnet_belt_y               1.099688    1.51870350   FALSE FALSE
magnet_belt_z               1.006369    2.32901845   FALSE FALSE
roll_arm                   52.338462   13.52563449   FALSE FALSE
pitch_arm                  87.256410   15.73234125   FALSE FALSE
yaw_arm                    33.029126   14.65701763   FALSE FALSE
total_accel_arm             1.024526    0.33635715   FALSE FALSE
var_accel_arm               5.500000    2.01304658   FALSE FALSE
avg_roll_arm               77.000000    1.68178575   FALSE  TRUE
stddev_roll_arm            77.000000    1.68178575   FALSE  TRUE
var_roll_arm               77.000000    1.68178575   FALSE  TRUE
avg_pitch_arm              77.000000    1.68178575   FALSE  TRUE
stddev_pitch_arm           77.000000    1.68178575   FALSE  TRUE
var_pitch_arm              77.000000    1.68178575   FALSE  TRUE
avg_yaw_arm                77.000000    1.68178575   FALSE  TRUE
stddev_yaw_arm             80.000000    1.66649679   FALSE  TRUE
var_yaw_arm                80.000000    1.66649679   FALSE  TRUE
gyros_arm_x                 1.015504    3.27693405   FALSE FALSE
gyros_arm_y                 1.454369    1.91621649   FALSE FALSE
gyros_arm_z                 1.110687    1.26388747   FALSE FALSE
accel_arm_x                 1.017341    3.95984099   FALSE FALSE
accel_arm_y                 1.140187    2.73672409   FALSE FALSE
accel_arm_z                 1.128000    4.03628580   FALSE FALSE
magnet_arm_x                1.000000    6.82397309   FALSE FALSE
magnet_arm_y                1.056818    4.44399144   FALSE FALSE
magnet_arm_z                1.036364    6.44684538   FALSE FALSE
kurtosis_roll_arm         246.358974    1.68178575   FALSE  TRUE
kurtosis_picth_arm        240.200000    1.67159311   FALSE  TRUE
kurtosis_yaw_arm         1746.909091    2.01304658   FALSE  TRUE
skewness_roll_arm         249.558442    1.68688207   FALSE  TRUE
skewness_pitch_arm        240.200000    1.67159311   FALSE  TRUE
skewness_yaw_arm         1746.909091    2.01304658   FALSE  TRUE
max_roll_arm               25.666667    1.47793293   FALSE  TRUE
max_picth_arm              12.833333    1.34033228   FALSE FALSE
max_yaw_arm                 1.227273    0.25991234   FALSE FALSE
min_roll_arm               19.250000    1.41677709   FALSE  TRUE
min_pitch_arm              19.250000    1.47793293   FALSE  TRUE
min_yaw_arm                 1.000000    0.19366018   FALSE FALSE
amplitude_roll_arm         25.666667    1.55947406   FALSE  TRUE
amplitude_pitch_arm        20.000000    1.49831821   FALSE  TRUE
amplitude_yaw_arm           1.037037    0.25991234   FALSE FALSE
roll_dumbbell               1.022388   84.20650290   FALSE FALSE
pitch_dumbbell              2.277372   81.74498012   FALSE FALSE
yaw_dumbbell                1.132231   83.48282540   FALSE FALSE
kurtosis_roll_dumbbell   3843.200000    2.02833554   FALSE  TRUE
kurtosis_picth_dumbbell  9608.000000    2.04362450   FALSE  TRUE
kurtosis_yaw_dumbbell      47.330049    0.01019264   FALSE  TRUE
skewness_roll_dumbbell   4804.000000    2.04362450   FALSE  TRUE
skewness_pitch_dumbbell  9608.000000    2.04872082   FALSE  TRUE
skewness_yaw_dumbbell      47.330049    0.01019264   FALSE  TRUE
max_roll_dumbbell           1.000000    1.72255631   FALSE FALSE
max_picth_dumbbell          1.333333    1.72765263   FALSE FALSE
max_yaw_dumbbell          960.800000    0.37203139   FALSE  TRUE
min_roll_dumbbell           1.000000    1.69197839   FALSE FALSE
min_pitch_dumbbell          1.666667    1.81429008   FALSE FALSE
min_yaw_dumbbell          960.800000    0.37203139   FALSE  TRUE
amplitude_roll_dumbbell     8.000000    1.97227602   FALSE FALSE
amplitude_pitch_dumbbell    8.000000    1.95189073   FALSE FALSE
amplitude_yaw_dumbbell     47.920200    0.01528896   FALSE  TRUE
total_accel_dumbbell        1.072634    0.21914178   FALSE FALSE
var_accel_dumbbell          6.000000    1.95698706   FALSE FALSE
avg_roll_dumbbell           1.000000    2.02323922   FALSE FALSE
stddev_roll_dumbbell       16.000000    1.99266130   FALSE FALSE
var_roll_dumbbell          16.000000    1.99266130   FALSE FALSE
avg_pitch_dumbbell          1.000000    2.02323922   FALSE FALSE
stddev_pitch_dumbbell      16.000000    1.99266130   FALSE FALSE
var_pitch_dumbbell         16.000000    1.99266130   FALSE FALSE
avg_yaw_dumbbell            1.000000    2.02323922   FALSE FALSE
stddev_yaw_dumbbell        16.000000    1.99266130   FALSE FALSE
var_yaw_dumbbell           16.000000    1.99266130   FALSE FALSE
gyros_dumbbell_x            1.003268    1.22821323   FALSE FALSE
gyros_dumbbell_y            1.264957    1.41677709   FALSE FALSE
gyros_dumbbell_z            1.060100    1.04984201   FALSE FALSE
accel_dumbbell_x            1.018018    2.16593619   FALSE FALSE
accel_dumbbell_y            1.053061    2.37488533   FALSE FALSE
accel_dumbbell_z            1.133333    2.08949139   FALSE FALSE
magnet_dumbbell_x           1.098266    5.74864948   FALSE FALSE
magnet_dumbbell_y           1.197740    4.30129447   FALSE FALSE
magnet_dumbbell_z           1.020833    3.44511263   FALSE FALSE
roll_forearm               11.589286   11.08959331   FALSE FALSE
pitch_forearm              65.983051   14.85577413   FALSE FALSE
yaw_forearm                15.322835   10.14677403   FALSE FALSE
kurtosis_roll_forearm     228.761905    1.64101519   FALSE  TRUE
kurtosis_picth_forearm    226.070588    1.64611151   FALSE  TRUE
kurtosis_yaw_forearm       47.330049    0.01019264   FALSE  TRUE
skewness_roll_forearm     231.518072    1.64611151   FALSE  TRUE
skewness_pitch_forearm    226.070588    1.62572623   FALSE  TRUE
skewness_yaw_forearm       47.330049    0.01019264   FALSE  TRUE
max_roll_forearm           27.666667    1.38110284   FALSE  TRUE
max_picth_forearm           2.964286    0.78992967   FALSE FALSE
max_yaw_forearm           228.761905    0.22933442   FALSE  TRUE
min_roll_forearm           27.666667    1.37091020   FALSE  TRUE
min_pitch_forearm           2.862069    0.87147080   FALSE FALSE
min_yaw_forearm           228.761905    0.22933442   FALSE  TRUE
amplitude_roll_forearm     20.750000    1.49322189   FALSE  TRUE
amplitude_pitch_forearm     3.269231    0.93262664   FALSE FALSE
amplitude_yaw_forearm      59.677019    0.01528896   FALSE  TRUE
total_accel_forearm         1.128928    0.35674243   FALSE FALSE
var_accel_forearm           3.500000    2.03343186   FALSE FALSE
avg_roll_forearm           27.666667    1.64101519   FALSE  TRUE
stddev_roll_forearm        87.000000    1.63082255   FALSE  TRUE
var_roll_forearm           87.000000    1.63082255   FALSE  TRUE
avg_pitch_forearm          83.000000    1.65120783   FALSE  TRUE
stddev_pitch_forearm       41.500000    1.64611151   FALSE  TRUE
var_pitch_forearm          83.000000    1.65120783   FALSE  TRUE
avg_yaw_forearm            83.000000    1.65120783   FALSE  TRUE
stddev_yaw_forearm         85.000000    1.64101519   FALSE  TRUE
var_yaw_forearm            85.000000    1.64101519   FALSE  TRUE
gyros_forearm_x             1.059273    1.51870350   FALSE FALSE
gyros_forearm_y             1.036554    3.77637346   FALSE FALSE
gyros_forearm_z             1.122917    1.56457038   FALSE FALSE
accel_forearm_x             1.126437    4.04647844   FALSE FALSE
accel_forearm_y             1.059406    5.11160942   FALSE FALSE
accel_forearm_z             1.006250    2.95586586   FALSE FALSE
magnet_forearm_x            1.012346    7.76679238   FALSE FALSE
magnet_forearm_y            1.246914    9.54031189   FALSE FALSE
magnet_forearm_z            1.000000    8.57710733   FALSE FALSE
classe                      1.469581    0.02548160   FALSE FALSE
uselessFeatures<-subset(nearzerovals, nearzerovals$nzv==TRUE)
 uselessFeatures
                         freqRatio percentUnique zeroVar  nzv
kurtosis_roll_belt      1921.60000    2.02323922   FALSE TRUE
kurtosis_picth_belt      600.50000    1.61553358   FALSE TRUE
kurtosis_yaw_belt         47.33005    0.01019264   FALSE TRUE
skewness_roll_belt      2135.11111    2.01304658   FALSE TRUE
skewness_roll_belt.1     600.50000    1.72255631   FALSE TRUE
skewness_yaw_belt         47.33005    0.01019264   FALSE TRUE
max_yaw_belt             640.53333    0.34654979   FALSE TRUE
min_yaw_belt             640.53333    0.34654979   FALSE TRUE
amplitude_yaw_belt        50.04167    0.02038528   FALSE TRUE
avg_roll_arm              77.00000    1.68178575   FALSE TRUE
stddev_roll_arm           77.00000    1.68178575   FALSE TRUE
var_roll_arm              77.00000    1.68178575   FALSE TRUE
avg_pitch_arm             77.00000    1.68178575   FALSE TRUE
stddev_pitch_arm          77.00000    1.68178575   FALSE TRUE
var_pitch_arm             77.00000    1.68178575   FALSE TRUE
avg_yaw_arm               77.00000    1.68178575   FALSE TRUE
stddev_yaw_arm            80.00000    1.66649679   FALSE TRUE
var_yaw_arm               80.00000    1.66649679   FALSE TRUE
kurtosis_roll_arm        246.35897    1.68178575   FALSE TRUE
kurtosis_picth_arm       240.20000    1.67159311   FALSE TRUE
kurtosis_yaw_arm        1746.90909    2.01304658   FALSE TRUE
skewness_roll_arm        249.55844    1.68688207   FALSE TRUE
skewness_pitch_arm       240.20000    1.67159311   FALSE TRUE
skewness_yaw_arm        1746.90909    2.01304658   FALSE TRUE
max_roll_arm              25.66667    1.47793293   FALSE TRUE
min_roll_arm              19.25000    1.41677709   FALSE TRUE
min_pitch_arm             19.25000    1.47793293   FALSE TRUE
amplitude_roll_arm        25.66667    1.55947406   FALSE TRUE
amplitude_pitch_arm       20.00000    1.49831821   FALSE TRUE
kurtosis_roll_dumbbell  3843.20000    2.02833554   FALSE TRUE
kurtosis_picth_dumbbell 9608.00000    2.04362450   FALSE TRUE
kurtosis_yaw_dumbbell     47.33005    0.01019264   FALSE TRUE
skewness_roll_dumbbell  4804.00000    2.04362450   FALSE TRUE
skewness_pitch_dumbbell 9608.00000    2.04872082   FALSE TRUE
skewness_yaw_dumbbell     47.33005    0.01019264   FALSE TRUE
max_yaw_dumbbell         960.80000    0.37203139   FALSE TRUE
min_yaw_dumbbell         960.80000    0.37203139   FALSE TRUE
amplitude_yaw_dumbbell    47.92020    0.01528896   FALSE TRUE
kurtosis_roll_forearm    228.76190    1.64101519   FALSE TRUE
kurtosis_picth_forearm   226.07059    1.64611151   FALSE TRUE
kurtosis_yaw_forearm      47.33005    0.01019264   FALSE TRUE
skewness_roll_forearm    231.51807    1.64611151   FALSE TRUE
skewness_pitch_forearm   226.07059    1.62572623   FALSE TRUE
skewness_yaw_forearm      47.33005    0.01019264   FALSE TRUE
max_roll_forearm          27.66667    1.38110284   FALSE TRUE
max_yaw_forearm          228.76190    0.22933442   FALSE TRUE
min_roll_forearm          27.66667    1.37091020   FALSE TRUE
min_yaw_forearm          228.76190    0.22933442   FALSE TRUE
amplitude_roll_forearm    20.75000    1.49322189   FALSE TRUE
amplitude_yaw_forearm     59.67702    0.01528896   FALSE TRUE
avg_roll_forearm          27.66667    1.64101519   FALSE TRUE
stddev_roll_forearm       87.00000    1.63082255   FALSE TRUE
var_roll_forearm          87.00000    1.63082255   FALSE TRUE
avg_pitch_forearm         83.00000    1.65120783   FALSE TRUE
stddev_pitch_forearm      41.50000    1.64611151   FALSE TRUE
var_pitch_forearm         83.00000    1.65120783   FALSE TRUE
avg_yaw_forearm           83.00000    1.65120783   FALSE TRUE
stddev_yaw_forearm        85.00000    1.64101519   FALSE TRUE
var_yaw_forearm           85.00000    1.64101519   FALSE TRUE
```
The new data frame is now down to 94 possible predictors.

```{}
> dim(trData3)
[1] 19622    94
```
Using trData3, I partitioned the data into a training set and testing set using y=trData3$classe and p=0.6.  I used 2323 as the seed.

```{}
> dim(training_set)
[1] 11776    94
> dim(testing_set)
[1] 7846   94
```


To determine if there is a subset of the 94 that would be best suited for using in a classification prediction, I next generated a classification tree using rpart to see which features of the training data are deemed to be the most discriminant for categorization purposes.

```{}
library(rpart)
tree<-rpart(classe~.,data=training_set, method="class")
> tree
n= 11776 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

    1) root 11776 8428 A (0.28 0.19 0.17 0.16 0.18)  
      2) roll_belt< 130.5 10777 7439 A (0.31 0.21 0.19 0.18 0.11)  
        4) pitch_forearm< -33.35 956    8 A (0.99 0.0084 0 0 0) *
        5) pitch_forearm>=-33.35 9821 7431 A (0.24 0.23 0.21 0.2 0.12)  
         10) roll_forearm< 123.5 6292 4121 A (0.35 0.24 0.15 0.19 0.07)  
           20) magnet_dumbbell_y< 437.5 5166 3055 A (0.41 0.18 0.18 0.17 0.06)  
             40) magnet_dumbbell_z< -27.5 1733  568 A (0.67 0.21 0.012 0.076 0.027)  
               80) roll_forearm>=-137.5 1455  318 A (0.78 0.18 0.012 0.025 0.0048) *
               81) roll_forearm< -137.5 278  165 B (0.1 0.41 0.011 0.34 0.14) *
             41) magnet_dumbbell_z>=-27.5 3433 2487 A (0.28 0.16 0.27 0.22 0.077)  
               82) accel_dumbbell_y>=-40.5 3002 2059 A (0.31 0.18 0.18 0.24 0.083)  
                164) yaw_belt>=169.5 404   44 A (0.89 0.045 0 0.064 0) *
                165) yaw_belt< 169.5 2598 1899 D (0.22 0.2 0.21 0.27 0.095)  
                  330) pitch_belt< -42.95 305   63 B (0.023 0.79 0.1 0.049 0.03) *
                  331) pitch_belt>=-42.95 2293 1609 D (0.25 0.12 0.22 0.3 0.1)  
                    662) roll_belt>=125.5 537  239 C (0.39 0.037 0.55 0.017 0.0037)  
                     1324) magnet_belt_z< -323.5 179    5 A (0.97 0 0.017 0 0.011) *
                     1325) magnet_belt_z>=-323.5 358   63 C (0.095 0.056 0.82 0.025 0) *
                    663) roll_belt< 125.5 1756 1081 D (0.21 0.15 0.12 0.38 0.13)  
                     1326) pitch_belt>=1.215 1106  839 A (0.24 0.22 0.13 0.22 0.19)  
                       2652) yaw_forearm>=-94.65 867  600 A (0.31 0.26 0.12 0.082 0.23)  
                         5304) accel_dumbbell_z< 21.5 495  247 A (0.5 0.2 0.21 0.065 0.026)  
                          10608) magnet_forearm_z>=-125.5 337   93 A (0.72 0.15 0.021 0.086 0.024) *
                          10609) magnet_forearm_z< -125.5 158   60 C (0.025 0.3 0.62 0.019 0.032) *
                         5305) accel_dumbbell_z>=21.5 372  185 E (0.051 0.34 0.0027 0.1 0.5) *
                       2653) yaw_forearm< -94.65 239   69 D (0 0.084 0.15 0.71 0.05) *
                     1327) pitch_belt< 1.215 650  216 D (0.16 0.032 0.11 0.67 0.038)  
                       2654) yaw_arm< -96.65 92    0 A (1 0 0 0 0) *
                       2655) yaw_arm>=-96.65 558  124 D (0.016 0.038 0.12 0.78 0.045) *
               83) accel_dumbbell_y< -40.5 431   55 C (0.007 0.049 0.87 0.035 0.037) *
           21) magnet_dumbbell_y>=437.5 1126  559 B (0.053 0.5 0.026 0.3 0.12)  
             42) total_accel_dumbbell>=5.5 673  179 B (0.089 0.73 0.043 0.0074 0.13) *
             43) total_accel_dumbbell< 5.5 453  118 D (0 0.16 0 0.74 0.099) *
         11) roll_forearm>=123.5 3529 2442 C (0.062 0.22 0.31 0.2 0.21)  
           22) magnet_dumbbell_y< 290.5 1819  930 C (0.087 0.14 0.49 0.15 0.14)  
             44) magnet_forearm_z< -251.5 133   30 A (0.77 0.083 0 0.045 0.098) *
             45) magnet_forearm_z>=-251.5 1686  797 C (0.033 0.15 0.53 0.15 0.14)  
               90) pitch_belt>=26.15 117   24 B (0.11 0.79 0.017 0 0.077) *
               91) pitch_belt< 26.15 1569  682 C (0.027 0.098 0.57 0.17 0.14) *
           23) magnet_dumbbell_y>=290.5 1710 1198 B (0.035 0.3 0.12 0.26 0.28)  
             46) accel_forearm_x>=-101.5 1191  756 B (0.026 0.37 0.15 0.1 0.36)  
               92) roll_belt>=-0.83 982  547 B (0.032 0.44 0.18 0.086 0.26) *
               93) roll_belt< -0.83 209   39 E (0 0 0 0.19 0.81) *
             47) accel_forearm_x< -101.5 519  189 D (0.056 0.15 0.039 0.64 0.12) *
      3) roll_belt>=130.5 999   10 E (0.01 0 0 0 0.99) *
```
Based on the tree nodes, I came up with a set of 16 predictors:
roll_belt, pitch_belt, yaw_belt, roll_forearm, pitch_forearm, yaw_forearm,
magnet_dumbbell_z, magnet_dumbbell_y, magnetf_forearm_z, magnet_belt_z,
accel_dumbbell_z, accel_dumbbell_y, yaw_arm, total_accel_dumbbell,
accel_forearm_z, accel_forearm_x

Next, I combined these predictors to train a Random Forest Model using 10-fold cross-validation and conditionalX preProcessing.  I chose Random Forest for its utility in classification problems.  I used 10-fold because it is the default which seemed more than adequate based on the sample size.  I used conditionalx because we are trying to predict 1 outcome that is based on columns of 'x' conditioned on the levels of 'y'.

```{}
> set.seed(2323)
> rfModel<-train(classe~roll_belt + pitch_belt + yaw_belt + roll_forearm + pitch_forearm + 
yaw_forearm + magnet_dumbbell_z + magnet_dumbbell_y + magnet_forearm_z + magnet_belt_z + 
accel_dumbbell_z + accel_dumbbell_y + yaw_arm + total_accel_dumbbell + accel_forearm_z + 
accel_forearm_x, data=training_set, method="rf", preProcess="conditionalX", trControl=trainControl
(method="cv"))
> print(rfModel)
Random Forest 

11776 samples
   93 predictor
    5 classes: 'A', 'B', 'C', 'D', 'E' 

Pre-processing: conditionalX (16) 
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 10598, 10597, 10599, 10598, 10599, 10599, ... 
Resampling results across tuning parameters:

  mtry  Accuracy   Kappa      Accuracy SD  Kappa SD   
   2    0.9910839  0.9887206  0.003233360  0.004091344
   9    0.9887914  0.9858213  0.003460698  0.004379255
  16    0.9827629  0.9781943  0.004558611  0.005770612

Accuracy was used to select the optimal model using  the largest value.
The final value used for the model was mtry = 2. 
```
I next used the fitted model to predict classe on the testing set:
```{}
> classPredictions<-predict(rfModel, testing_set)
```
To check the accuracy of the model, I generated a confusion matrix using the predicted classes vs. the classes in the testing set:
```{}
 cm<-confusionMatrix(classPredictions, testing_set$classe)
> cm
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 2219    9    0    0    0
         B   12 1498   11    0    6
         C    1   10 1350    7    3
         D    0    0    7 1279    4
         E    0    1    0    0 1429

Overall Statistics
                                          
               Accuracy : 0.991           
                 95% CI : (0.9886, 0.9929)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.9886          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9942   0.9868   0.9868   0.9946   0.9910
Specificity            0.9984   0.9954   0.9968   0.9983   0.9998
Pos Pred Value         0.9960   0.9810   0.9847   0.9915   0.9993
Neg Pred Value         0.9977   0.9968   0.9972   0.9989   0.9980
Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
Detection Rate         0.2828   0.1909   0.1721   0.1630   0.1821
Detection Prevalence   0.2840   0.1946   0.1747   0.1644   0.1823
Balanced Accuracy      0.9963   0.9911   0.9918   0.9964   0.9954
> 
```

Turns out the model accuracy is 99%.
The in sample error is virtually non-existent, the model Accuracy is 1 on the training data:
```{}
> insamplepredictions<-predict(rfModel, training_set)
> cm2<-confusionMatrix(insamplepredictions, training_set$classe)

Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 3348    0    0    0    0
         B    0 2279    0    0    0
         C    0    0 2054    0    0
         D    0    0    0 1930    0
         E    0    0    0    0 2165

Overall Statistics
                                     
               Accuracy : 1          
                 95% CI : (0.9997, 1)
    No Information Rate : 0.2843     
    P-Value [Acc > NIR] : < 2.2e-16  
                                     
                  Kappa : 1          
 Mcnemar's Test P-Value : NA         

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            1.0000   1.0000   1.0000   1.0000   1.0000
Specificity            1.0000   1.0000   1.0000   1.0000   1.0000
Pos Pred Value         1.0000   1.0000   1.0000   1.0000   1.0000
Neg Pred Value         1.0000   1.0000   1.0000   1.0000   1.0000
Prevalence             0.2843   0.1935   0.1744   0.1639   0.1838
Detection Rate         0.2843   0.1935   0.1744   0.1639   0.1838
Detection Prevalence   0.2843   0.1935   0.1744   0.1639   0.1838
Balanced Accuracy      1.0000   1.0000   1.0000   1.0000   1.0000
> 
```
Next, I used the model to predict the classe on the pml-testing data which I loaded into a data frame called testcasedata. I then appended the predicted outcome to the data.
```{}
testcasepredictions<-predict(rfModel, testcasedata)
testcasedata$classe<-testcasepredictions
> dim(testcasedata)
[1]  20 161

> head(testcasedata[,c("problem_id","classe")])
  problem_id classe
1          1      B
2          2      A
3          3      B
4          4      A
5          5      A
6          6      E
> tail(testcasedata[,c("problem_id","classe")])
   problem_id classe
15         15      E
16         16      E
17         17      A
18         18      B
19         19      B
20         20      B
```

Finally, given the problem # and machine learning predicted classe, I am now able to answer the quiz questions.
